### ISSUE TITLE
Create Figma Page for Campus Tab

### ISSUE THREAD

**Issue by ryanmarshallmc** [sharingexcess/sharingexcess.com#17]
The Campus tab does not contain all the content from the previous SquareSpace site. Let's work with marketing (probably specifically Cara and Victoria) and Valentina as needed to create a prototype for a new campus page with Desktop and Mobile specs. As a general thought, less is more in terms of content (our HotJar data is showing scroll rates are not great, so simple is better when possible).

**Comment by lukeshinnn** [comment]
- Introduce Campus on Home page (make photo heavy, and talk about the WHY and the NUMBER OF STUDENTS IN ALL SE CHAPTERS INVOLVED) (something talking about the impact students make on campuses that distribution would otherwise not reach. and then something like "Join our team of 1,000+ students to help Sharing Excess fight food insecurity" (with link to campus page))
- Impact numbers for food distributed on campuses/campus popups (and numbers of student chapters)
- Different chapter activities that students can get involved in (impact, fundraise, research or active initiatives?)

LAYOUT: 
- TOP OF  PAGE: explaining our WHY and our OBJECTIVE with working with universities (one sentence) "WE believe colleges and universities play a major role in food sharing. Campus does not focus on distribution, but rather help move the mission of Sharing Excess through respective on-campus and off-campus programs and activities." (Off campus would be like the national network/nonprofit) Very image-driven explanation of WHY we work with chapter
- Then explain the WORK we do with chapters (circle or square images with words written overtop/underneath with a quick description of blurb. For example, "food pantry" then you can click onto it to see more information or interest form"
- OUR CURRENT CHAPTERS
- CALL TO ACTION (START YOUR OWN CHAPTER/GET INVOLVED) that also includes administrative resources catered to staff and faculty (to show that teachers can also start a chapter)
- include information about WHAT SE PROVIDES TO CHAPTERS (services we provide, technology, campus coordinators, research, etc.)
- POTENTIAL FOOTER: Interested in joining our national team as an internship? Here's some info! (or maybe include in the SERVICES PROVIDED section)

- scatter some student quotes and affirmations throughout
- include Campus Video somewhere

- need to update list of current chapters

- What kind of programs we help students establish (educational, popups, etc.)
- (Think of catering to professors and university leaders that may also want to start a chapter, in addition to students)
